CREATE TABLE IF NOT EXISTS STUDENT
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   `BRANCH` VARCHAR (20) NOT NULL UNIQUE,
    `CARD_NUMBER` VARCHAR (300) NOT NULL UNIQUE,
     `FIRST_NAME` VARCHAR (20) NOT NULL UNIQUE,
   `LAST_NAME` VARCHAR (20) NOT NULL UNIQUE,
   `SEMESTER` VARCHAR (20) NOT NULL UNIQUE,
   `PASSWORD` VARCHAR (300) NOT NULL UNIQUE,
   `USER_NAME` VARCHAR (300) NOT NULL UNIQUE,
   PRIMARY KEY (ID)
   
);