version: "3"
services:
  javatechiemongodb:
    image: mongo:latest
    container_name: "BookStore"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 9080:9080
    links:
      - BookStore