version: "3"
services:
  BookStore:
    image: mongo:latest
    container_name: "BookStore"
    ports:
      - 27017:27017
  springss-mongodb:
    image: springs-mongodb:1.0
    container_name: springss-mongodb
    ports:
      - 9080:9080
    links:
      - BookStore