CREATE TABLE IF NOT EXISTS COLLEGE
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   `TEACHERS_ID` VARCHAR (20) NOT NULL UNIQUE,
   `COLLEGE_NAME` VARCHAR (300) NOT NULL,
   `STATUS` VARCHAR (10) NOT NULL,
    `COLLEGE_CODE` VARCHAR (20) NOT NULL,
    `COLLEGE_TYPE` VARCHAR (20),
   STUDENT_ID BIGINT NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);